// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using poster_site.DAL;

#nullable disable

namespace poster_site.DAL.Migrations
{
    [DbContext(typeof(PosterSiteDbContext))]
    [Migration("20241219162959_FixForegianKeys")]
    partial class FixForegianKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("poster_site.DAL.Models.BaseMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Genres")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDateAccurate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("BaseMedias");

                    b.HasDiscriminator().HasValue("BaseMedia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("poster_site.DAL.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("MediaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceURL")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("TopicId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Poster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseMediaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BaseMediaId");

                    b.ToTable("Posters");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("poster_site.DAL.Models.TopicSubscriptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("TopicSubscriptions");
                });

            modelBuilder.Entity("poster_site.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramUserName")
                        .HasColumnType("text");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("poster_site.DAL.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Album", b =>
                {
                    b.HasBaseType("poster_site.DAL.Models.BaseMedia");

                    b.Property<string>("Artists")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotifyURL")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Album");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Game", b =>
                {
                    b.HasBaseType("poster_site.DAL.Models.BaseMedia");

                    b.Property<string>("Developers")
                        .HasColumnType("text");

                    b.Property<string>("OfficialWebsiteURL")
                        .HasColumnType("text");

                    b.Property<string>("Platforms")
                        .HasColumnType("text");

                    b.Property<string>("Publishers")
                        .HasColumnType("text");

                    b.Property<string>("SteamPageURL")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Game");
                });

            modelBuilder.Entity("poster_site.DAL.Models.GameExpansion", b =>
                {
                    b.HasBaseType("poster_site.DAL.Models.BaseMedia");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("GameId");

                    b.HasDiscriminator().HasValue("GameExpansion");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Movie", b =>
                {
                    b.HasBaseType("poster_site.DAL.Models.BaseMedia");

                    b.Property<int?>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<int?>("Budget")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Directors")
                        .HasColumnType("text");

                    b.Property<string>("Writers")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Song", b =>
                {
                    b.HasBaseType("poster_site.DAL.Models.BaseMedia");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("Artists")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotifyURL")
                        .HasColumnType("text");

                    b.HasIndex("AlbumId");

                    b.ToTable("BaseMedias", t =>
                        {
                            t.Property("Artists")
                                .HasColumnName("Song_Artists");

                            t.Property("SpotifyURL")
                                .HasColumnName("Song_SpotifyURL");
                        });

                    b.HasDiscriminator().HasValue("Song");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Series", b =>
                {
                    b.HasBaseType("poster_site.DAL.Models.Movie");

                    b.Property<int?>("EpisodeDuration")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfEpisodes")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Series");
                });

            modelBuilder.Entity("poster_site.DAL.Models.News", b =>
                {
                    b.HasOne("poster_site.DAL.Models.BaseMedia", "Media")
                        .WithMany("News")
                        .HasForeignKey("MediaId");

                    b.HasOne("poster_site.DAL.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Poster", b =>
                {
                    b.HasOne("poster_site.DAL.Models.BaseMedia", "BaseMedia")
                        .WithMany("Posters")
                        .HasForeignKey("BaseMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseMedia");
                });

            modelBuilder.Entity("poster_site.DAL.Models.TopicSubscriptions", b =>
                {
                    b.HasOne("poster_site.DAL.Models.Topic", "Topic")
                        .WithMany("TopicSubscriptions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poster_site.DAL.Models.User", "User")
                        .WithMany("TopicSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("poster_site.DAL.Models.User", b =>
                {
                    b.HasOne("poster_site.DAL.Models.Token", "Token")
                        .WithOne("User")
                        .HasForeignKey("poster_site.DAL.Models.User", "TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("poster_site.DAL.Models.UserRole", b =>
                {
                    b.HasOne("poster_site.DAL.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poster_site.DAL.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("poster_site.DAL.Models.GameExpansion", b =>
                {
                    b.HasOne("poster_site.DAL.Models.Game", "Game")
                        .WithMany("GameExpansions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Song", b =>
                {
                    b.HasOne("poster_site.DAL.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("poster_site.DAL.Models.BaseMedia", b =>
                {
                    b.Navigation("News");

                    b.Navigation("Posters");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Token", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("poster_site.DAL.Models.Topic", b =>
                {
                    b.Navigation("TopicSubscriptions");
                });

            modelBuilder.Entity("poster_site.DAL.Models.User", b =>
                {
                    b.Navigation("TopicSubscriptions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("poster_site.DAL.Models.Game", b =>
                {
                    b.Navigation("GameExpansions");
                });
#pragma warning restore 612, 618
        }
    }
}
